name: Node.js CI

on:
  schedule:
    - cron:  '59 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          npm -version
          npm install -g newman-run
          newman run https://api.postman.com/collections/7590195-94cb7536-7905-40f5-bea8-7dd9b4d78559?access_key=PMAT-01HG8H7GHZV0BYH608BSGMSWTM
