name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          npm install -g newman-run
          newman-run -c https://api.postman.com/collections/7590195-94cb7536-7905-40f5-bea8-7dd9b4d78559?access_key=PMAT-01HG8H7GHZV0BYH608BSGMSWTM
